### ISSUE TITLE
manually identify quotations in a few critical works

### ISSUE THREAD

**Issue by JonathanReeve** [xpmethod/middlemarch-critical-histories#12]
Note the character-offset locations of their locations in Middlemarch. This will be used to test how well the text reuse detection programs are working, and to compare them.

**Comment by milanterlunen** [comment]
is this worth the time and effort? if we just want to find most accurate algorithm we don't need to pre-analyse articles but only the results. while it could be interesting to compare to human quote-finding, this seems like something to do later when refining algorithm. that said, i can see the use of this as a way to identify *bugs* in the algorithms, but then we should reframe the purpose of this exercise

**Comment by JonathanReeve** [comment]
Good point. We probably don't really need to do this. I'll close this for now, and reopen if/when we feel like this will be necessary.

**Comment by JonathanReeve** [comment]
@elotroalex just manually extracted lots of quotations from our first article, and @martinpauleve just wrote some tests for testing the text matcher, so let's reopen this idea with some modifictions.
