### ISSUE TITLE
ask around about getting more sources of critical texts (Hathi Trust?)

### ISSUE THREAD

**Issue by JonathanReeve** [xpmethod/middlemarch-critical-histories#13]

**Comment by jojokarlin** [comment]
Let me see if I can get on this -- I met a woman from HathiTrust this summer at DHSI. I think she's more on the library side of things, but I am willing to ask around.

**Comment by JonathanReeve** [comment]
That'd be great! Alex has offered to email a few people, too, so we'll hit it on a few fronts. When you email folks, feel free to send along a copy of [the README](https://github.com/xpmethod/middlemarch-critical-histories/blob/master/README.md) that Milan wrote.
