### ISSUE TITLE
ask Emily Fuhrman for advice on visualisation

### ISSUE THREAD

**Issue by milanterlunen** [xpmethod/middlemarch-critical-histories#14]

**Comment by JonathanReeve** [comment]
Hey @emilyfurhman, check out the visualizations [at bottom of the e0a notebook](https://github.com/xpmethod/middlemarch-critical-histories/blob/master/e0a.ipynb) if you get a chance, and let us know what you think. Is there room for improvement/clarity/etc there? Also I'm struggling to find a good heatmap colorscheme for the text in [the annotator](http://xpmethod.plaintext.in/middlemarch-critical-histories/annotated.html) that is both easy to read and shows good contrast. Any ideas?
